In [1]:
import json
import pandas as pd
with open("./pitches.json") as f:
    j = json.load(f)


def prepare(arr):
    for page in arr:
        try:
            yield {"src_url": page["src_url"], "url": page["url"]["href"], **page["initialState"]["opportunity"]["opportunity"]}
        except:
            print("failed at ", page["url"]["href"])

data = prepare(j)
cc_full = pd.json_normalize(data)
cc_full

src_url  \
0     https://www.crowdcube.eu/investment/move-techn...   
1     https://www.crowdcube.eu/investment/hooked-foo...   
2     https://www.crowdcube.eu/investment/move-techn...   
3     https://www.crowdcube.eu/investment/vegan-shac...   
4     https://www.crowdcube.eu/investment/mapal-aera...   
...                                                 ...   
1233  https://www.crowdcube.eu/investment/crowdcube-...   
1234  https://www.crowdcube.eu/investment/crowdcube-...   
1235  https://www.crowdcube.eu/investment/crowdcube-...   
1236    https://www.crowdcube.eu/investment/sugru-21396   
1237  https://www.crowdcube.eu/investment/crowdcube-...   

                                                    url      id  \
0     https://www.crowdcube.eu/companies/move-techno...  bvLKxl   
1     https://www.crowdcube.eu/companies/hooked-food...  bJ1kdZ   
2     https://www.crowdcube.eu/companies/move-techno...  q4Mwol   
3     https://www.crowdcube.eu/companies/vegan-shack...  bXEeEq   
4     https://www.crowdcube.eu/companies/mapal-aerat...  qaE20q   
...                                                 ...     ...   
1233  https://www.crowdcube.eu/companies/crowdcube/p...  qno1vl   
1234  https://www.crowdcube.eu/companies/crowdcube/p...  qD0nPq   
1235  https://www.crowdcube.eu/companies/crowdcube/p...  lOPYXZ   
1236  https://www.crowdcube.eu/companies/sugru/pitch...  bgNOBZ   
1237  https://www.crowdcube.eu/companies/crowdcube/p...  l8nrkb   

                                    entr_title  \
0                                                
1     Tom Johansson, Peter Liu & Emil Wasteson   
2                                                
3                 Dimeji Sadiq and Saffron Mir   
4                                  Zeev Fisher   
...                                        ...   
1233                           Darren Westlake   
1234                           Darren Westlake   
1235                             Darren & Luke   
1236                    Jane ni Dhulchaointigh   
1237                             Darren & Luke   

      enable_email_notification_on_pitch_investment  primary_sector_id  \
0                                              True                  0   
1                                              True                  0   
2                                              True                  0   
3                                              True                  0   
4                                              True                  0   
...                                             ...                ...   
1233                                          False                  0   
1234                                          False                  0   
1235                                           True                  8   
1236                                           True                  4   
1237                                           True                  8   

      can_view  status  hidden  restricted  ...  the_financials.id  \
0         True  funded   False       False  ...                NaN   
1         True  funded   False       False  ...                NaN   
2         True  funded   False       False  ...                NaN   
3         True  funded   False       False  ...                NaN   
4         True  funded   False       False  ...                NaN   
...        ...     ...     ...         ...  ...                ...   
1233      True  funded   False       False  ...                NaN   
1234      True  funded   False       False  ...                NaN   
1235      True  funded   False       False  ...                NaN   
1236      True  funded   False       False  ...             vlK54b   
1237      True  funded   False       False  ...             nbXXEb   

                                 the_financials.content  \
0                                                   NaN   
1                                                   NaN   
2                         

In [2]:
cc_full.iloc[0].to_dict()

{'src_url': 'https://www.crowdcube.eu/investment/move-technologies-group-ltd-30261',
 'url': 'https://www.crowdcube.eu/companies/move-technologies-group-ltd/pitches/bvLKxl',
 'id': 'bvLKxl',
 'entr_title': '',
 'enable_email_notification_on_pitch_investment': True,
 'primary_sector_id': 0,
 'can_view': True,
 'status': 'funded',
 'hidden': False,
 'restricted': False,
 'pledges_only': False,
 'eis': ['no', 'yes', 'pending'],
 'seis': ['no', 'yes', 'pending'],
 'product': 'equity_share_price',
 'name': 'Move Technologies Group Ltd',
 'description': '',
 'images': [],
 'the_idea': nan,
 'highlights': [],
 'faqs': [],
 'expires_at': '1970-01-01 00:00:00',
 'currency': 'GBP',
 'custom_terms_and_conditions_url': None,
 'stripe_platform_account_id': '6Z5xlB',
 'translations_available': [],
 'regulators': [],
 'financial_promotion_date': None,
 'team_members': [],
 'is_open_for_early_access': False,
 'early_access_url': None,
 'early_access_summary_text': '',
 'call_to_action': 'Get early acc

In [3]:
old = pd.read_json("./old.json")
old["src_url"] = old["url"]
old[["investment.target","stats.investments.largest"]] = old[["investment.target","stats.investments.largest"]].map(lambda x: [x,pd.NA])
old.equity = old.equity.str.replace("%","").astype(float)
old

name  \
0                                     Cupris   
1                      The Halal Dining Club   
2                                   Sundried   
3                                    Revolut   
4                                VERTO HOMES   
..                                       ...   
353     Kammerling's Investment Holdings Ltd   
354                   The Rushmore Group Ltd   
355                   The Rushmore Group Ltd   
356  The Rushmore Group Ltd - Extended offer   
357                             Kammerling's   

                                                   url  \
0     https://www.crowdcube.eu/investment/cupris-21131   
1    https://www.crowdcube.eu/investment/the-halal-...   
2    https://www.crowdcube.eu/investment/sundried-1...   
3    https://www.crowdcube.eu/investment/revolut-21142   
4    https://www.crowdcube.eu/investment/verto-home...   
..                                                 ...   
353  https://www.crowdcube.eu/investment/kamm-sons-...   
354  https://www.crowdcube.eu/investment/the-rushmo...   
355  https://www.crowdcube.eu/investment/the-rushmo...   
356  https://www.crowdcube.eu/investment/the-rushmo...   
357  https://www.crowdcube.eu/investment/kamm-sons-...   

                                           description               status  \
0    Cupris has designed a medical device attachmen...  Successfully funded   
1    Present in London and Singapore, and backed by...  Successfully funded   
2    Sundried is a premium ethical activewear brand...  Successfully funded   
3    Revolut was launched by ex-finance professiona...  Successfully funded   
4    Verto Homes designs, builds and sells intellig...  Successfully funded   
..                                                 ...                  ...   
353  Kammerlings Ltd launched its unique 33% abv gi...  Successfully funded   
354  The Rushmore Group Ltd is the parent company o...  Successfully funded   
355  The Rushmore Group is the well-established own...  Successfully funded   
356  PLEASE NOTE: This is a private offer seeking t...  Successfully funded   
357  Kammerling’s is a totally new kind of alcoholi...  Successfully funded   

    investment.target  equity  stats.investors.total stats.investors.last  \
0      [500000, <NA>]   17.42                    357  2016-10-13 08:04:31   
1      [150000, <NA>]   16.70                     58  2016-08-18 13:44:37   
2      [125000, <NA>]   12.06                    197  2016-09-28 13:49:14   
3     [1030000, <NA>]    2.39                    433  2016-09-02 13:35:02   
4     [1000000, <NA>]   15.63                    491  2016-10-12 13:52:29   
..                ...     ...                    ...                  ...   
353    [325000, <NA>]   20.00                     65  2013-02-06 16:46:50   
354    [500000, <NA>]    4.61                     73  2013-05-03 12:17:11   
355   [1000000, <NA>]    0.00                    142  2011-11-19 14:11:01   
356    [500000, <NA>]    5.00                     69  2011-12-21 22:09:00   
357    [180000, <NA>]   23.00                     85  2011-10-13 19:51:03   

    stats.investments.largest  \
0              [200000, <NA>]   
1               [40000, <NA>]   
2               [40000, <NA>]   
3                [5000, <NA>]   
4              [500000, <NA>]   
..                        ...   
353            [225000, <NA>]   
354             [50000, <NA>]   
355             [30000, <NA>]   
356             [90000, <NA>]   
357            [125000, <NA>]   

                                               src_url  
0     https://www.crowdcube.eu/investment/cupris-21131  
1    https://www.crowdcube.eu/investment/the-halal-...  
2    https://www.crowdcube.eu/investment/sundried-1...  
3    https://www.crowdcube.eu/investment/revolut-21142  
4    https://www.crowdcube.eu/investment/verto-home...  
..                                                 ...  
353  https://www.crowdcube.eu/investment/kamm-sons-...  
354  https://www.crowdcube.eu/investmen

In [4]:
full = pd.concat([cc_full, old])
full

src_url  \
0    https://www.crowdcube.eu/investment/move-techn...   
1    https://www.crowdcube.eu/investment/hooked-foo...   
2    https://www.crowdcube.eu/investment/move-techn...   
3    https://www.crowdcube.eu/investment/vegan-shac...   
4    https://www.crowdcube.eu/investment/mapal-aera...   
..                                                 ...   
353  https://www.crowdcube.eu/investment/kamm-sons-...   
354  https://www.crowdcube.eu/investment/the-rushmo...   
355  https://www.crowdcube.eu/investment/the-rushmo...   
356  https://www.crowdcube.eu/investment/the-rushmo...   
357  https://www.crowdcube.eu/investment/kamm-sons-...   

                                                   url      id  \
0    https://www.crowdcube.eu/companies/move-techno...  bvLKxl   
1    https://www.crowdcube.eu/companies/hooked-food...  bJ1kdZ   
2    https://www.crowdcube.eu/companies/move-techno...  q4Mwol   
3    https://www.crowdcube.eu/companies/vegan-shack...  bXEeEq   
4    https://www.crowdcube.eu/companies/mapal-aerat...  qaE20q   
..                                                 ...     ...   
353  https://www.crowdcube.eu/investment/kamm-sons-...     NaN   
354  https://www.crowdcube.eu/investment/the-rushmo...     NaN   
355  https://www.crowdcube.eu/investment/the-rushmo...     NaN   
356  https://www.crowdcube.eu/investment/the-rushmo...     NaN   
357  https://www.crowdcube.eu/investment/kamm-sons-...     NaN   

                                   entr_title  \
0                                               
1    Tom Johansson, Peter Liu & Emil Wasteson   
2                                               
3                Dimeji Sadiq and Saffron Mir   
4                                 Zeev Fisher   
..                                        ...   
353                                       NaN   
354                                       NaN   
355                                       NaN   
356                                       NaN   
357                                       NaN   

    enable_email_notification_on_pitch_investment  primary_sector_id can_view  \
0                                            True                0.0     True   
1                                            True                0.0     True   
2                                            True                0.0     True   
3                                            True                0.0     True   
4                                            True                0.0     True   
..                                            ...                ...      ...   
353                                           NaN                NaN      NaN   
354                                           NaN                NaN      NaN   
355                                           NaN                NaN      NaN   
356                                           NaN                NaN      NaN   
357                                           NaN                NaN      NaN   

                  status hidden restricted  ... the_financials.id  \
0                 funded  False      False  ...               NaN   
1                 funded  False      False  ...               NaN   
2                 funded  False      False  ...               NaN   
3                 funded  False      False  ...               NaN   
4                 funded  False      False  ...               NaN   
..                   ...    ...        ...  ...               ...   
353  Successfully funded    NaN        NaN  ...               NaN   
354  Successfully funded    NaN        NaN  ...               NaN   
355  Successfully funded    NaN        NaN  ...               NaN   
356  Successfully funded    NaN        NaN  ...               NaN   
357  Successfully funded    NaN        NaN  ...               NaN   

    the_financials.content the_financials.media  \
0                      NaN                  NaN   
1                      NaN                  NaN   
2            

In [5]:
meta = pd.read_json("./pitches_meta.json")
meta

company       Date  \
0     https://www.crowdcube.eu/companies/cutbox-barbers 2023-12-06   
1       https://www.crowdcube.eu/companies/hooked-foods 2023-06-13   
2     https://www.crowdcube.eu/companies/mapal-aerat... 2023-06-13   
3     https://www.crowdcube.eu/companies/move-techno... 2023-09-06   
4     https://www.crowdcube.eu/companies/move-techno... 2023-09-06   
...                                                 ...        ...   
1847       https://www.crowdcube.eu/companies/kamm-sons 2012-12-20   
1848       https://www.crowdcube.eu/companies/kamm-sons 2011-10-13   
1849  https://www.crowdcube.eu/companies/the-rushmor... 2013-04-15   
1850  https://www.crowdcube.eu/companies/the-rushmor... 2011-12-21   
1851  https://www.crowdcube.eu/companies/the-rushmor... 2011-11-19   

           Amount No. of Investors  \
0     £491,242.90              139   
1     €638,736.61              171   
2     £463,814.41              427   
3         £57,200              132   
4        £932,850            1,071   
...           ...              ...   
1847     £325,000               65   
1848     £180,000               85   
1849     £500,000               73   
1850     £500,000               69   
1851   £1,025,000              142   

                                                    url  
0     https://www.crowdcube.eu/investment/cutbox-bar...  
1     https://www.crowdcube.eu/investment/hooked-foo...  
2     https://www.crowdcube.eu/investment/mapal-aera...  
3     https://www.crowdcube.eu/investment/move-techn...  
4     https://www.crowdcube.eu/investment/move-techn...  
...                                                 ...  
1847  https://www.crowdcube.eu/investment/kamm-sons-...  
1848  https://www.crowdcube.eu/investment/kamm-sons-...  
1849  https://www.crowdcube.eu/investment/the-rushmo...  
1850  https://www.crowdcube.eu/investment/the-rushmo...  
1851  https://www.crowdcube.eu/investment/the-rushmo...  

[1852 rows x 5 columns]

In [6]:
final_full = pd.merge(meta, full, left_on="url", right_on="src_url",
                      how="inner", suffixes=["_left", None], validate="1:m")
final_full

company       Date  \
0     https://www.crowdcube.eu/companies/cutbox-barbers 2023-12-06   
1       https://www.crowdcube.eu/companies/hooked-foods 2023-06-13   
2     https://www.crowdcube.eu/companies/mapal-aerat... 2023-06-13   
3     https://www.crowdcube.eu/companies/move-techno... 2023-09-06   
4     https://www.crowdcube.eu/companies/move-techno... 2023-09-06   
...                                                 ...        ...   
1591       https://www.crowdcube.eu/companies/kamm-sons 2012-12-20   
1592       https://www.crowdcube.eu/companies/kamm-sons 2011-10-13   
1593  https://www.crowdcube.eu/companies/the-rushmor... 2013-04-15   
1594  https://www.crowdcube.eu/companies/the-rushmor... 2011-12-21   
1595  https://www.crowdcube.eu/companies/the-rushmor... 2011-11-19   

           Amount No. of Investors  \
0     £491,242.90              139   
1     €638,736.61              171   
2     £463,814.41              427   
3         £57,200              132   
4        £932,850            1,071   
...           ...              ...   
1591     £325,000               65   
1592     £180,000               85   
1593     £500,000               73   
1594     £500,000               69   
1595   £1,025,000              142   

                                               url_left  \
0     https://www.crowdcube.eu/investment/cutbox-bar...   
1     https://www.crowdcube.eu/investment/hooked-foo...   
2     https://www.crowdcube.eu/investment/mapal-aera...   
3     https://www.crowdcube.eu/investment/move-techn...   
4     https://www.crowdcube.eu/investment/move-techn...   
...                                                 ...   
1591  https://www.crowdcube.eu/investment/kamm-sons-...   
1592  https://www.crowdcube.eu/investment/kamm-sons-...   
1593  https://www.crowdcube.eu/investment/the-rushmo...   
1594  https://www.crowdcube.eu/investment/the-rushmo...   
1595  https://www.crowdcube.eu/investment/the-rushmo...   

                                                src_url  \
0     https://www.crowdcube.eu/investment/cutbox-bar...   
1     https://www.crowdcube.eu/investment/hooked-foo...   
2     https://www.crowdcube.eu/investment/mapal-aera...   
3     https://www.crowdcube.eu/investment/move-techn...   
4     https://www.crowdcube.eu/investment/move-techn...   
...                                                 ...   
1591  https://www.crowdcube.eu/investment/kamm-sons-...   
1592  https://www.crowdcube.eu/investment/kamm-sons-...   
1593  https://www.crowdcube.eu/investment/the-rushmo...   
1594  https://www.crowdcube.eu/investment/the-rushmo...   
1595  https://www.crowdcube.eu/investment/the-rushmo...   

                                                    url      id  \
0     https://www.crowdcube.eu/companies/cutbox-barb...  lKnKBq   
1     https://www.crowdcube.eu/companies/hooked-food...  bJ1kdZ   
2     https://www.crowdcube.eu/companies/mapal-aerat...  qaE20q   
3     https://www.crowdcube.eu/companies/move-techno...  bvLKxl   
4     https://www.crowdcube.eu/companies/move-techno...  q4Mwol   
...                                                 ...     ...   
1591  https://www.crowdcube.eu/investment/kamm-sons-...     NaN   
1592  https://www.crowdcube.eu/investment/kamm-sons-...     NaN   
1593  https://www.crowdcube.eu/investment/the-rushmo...     NaN   
1594  https://www.crowdcube.eu/investment/the-rushmo...     NaN   
1595  https://www.crowdcube.eu/investment/the-rushmo...     NaN   

                                    entr_title  \
0                                    Louis, Oz   
1     Tom Johansson, Peter Liu & Emil Wasteson   
2                                  Zeev Fisher   
3                                                
4                                                
...                                        ...   
1591                                       NaN   
1592                                       NaN   
1593                                       NaN   
1594                       

In [7]:
money = [
    'valuation.pre',
    'valuation.post',
    'investment.current',
    'investment.target',
    'investment.minimum',
    'investment.maximum',
    'investment.multiple',
    'investment_fee.minimum',
    'investment_fee.maximum',
    'stats.investments.today',
    'stats.investments.yesterday',
    'stats.investments.last_7_days',
    'stats.investments.daily_average',
    'stats.investments.weekly_average',
    'stats.investments.largest',
    'stats.investments.last',
    'stats.investments.total',
    'stats.investments.last_hour',
    #'currency', 'rewards', 'shares', 'remaining_tax_relief_allocation'
]
final_full[money].dropna().head(2)

valuation.pre     valuation.post investment.current investment.target  \
0   [788787900, GBP]   [828787900, GBP]    [49124290, GBP]   [40000000, GBP]   
1  [1171704900, EUR]  [1227704900, EUR]    [63873661, EUR]   [56000000, EUR]   

  investment.minimum investment.maximum       investment.multiple  \
0        [3326, GBP]    [40000000, GBP]  [3325.721000000000, GBP]   
1        [1299, EUR]    [56000000, EUR]  [1298.956900000000, EUR]   

  investment_fee.minimum investment_fee.maximum stats.investments.today  \
0             [249, GBP]           [25000, GBP]                [0, GBP]   
1             [249, EUR]           [25000, EUR]             [1299, EUR]   

  stats.investments.yesterday stats.investments.last_7_days  \
0                    [0, GBP]                      [0, GBP]   
1                    [0, EUR]                   [1299, EUR]   

  stats.investments.daily_average stats.investments.weekly_average  \
0                   [893100, GBP]                   [7017700, GBP]   
1                  [1205100, EUR]                   [9124800, EUR]   

  stats.investments.largest stats.investments.last stats.investments.total  \
0           [38787800, GBP]           [13300, GBP]         [49124200, GBP]   
1           [25879100, EUR]            [1200, EUR]         [63873600, EUR]   

  stats.investments.last_hour  
0                    [0, GBP]  
1                    [0, EUR]

In [8]:
mark_up = [
    'description',
    'the_idea.content',
    "the_people.content",
]
final_full[mark_up].dropna().head(2)

description  \
2  Regulations require all municipal and industri...   
6  Katrick Technologies have designed & patented ...   

                                    the_idea.content  \
2  <p>Millions of dollars are wasted each year th...   
6  <p>Based on years of research, our mission is ...   

                                  the_people.content  
2  <p><strong>Zeev Fisher, CEO and co-founder</st...  
6  <p>Our experienced senior management team comp...

In [9]:
complex = [
    'highlights',
    'faqs',
    'team_members',
    'rewards',
    'shares',
    'regulators',
    'remaining_tax_relief_allocation',
]
final_full[complex].dropna().head(2)
list(final_full[complex].iloc[0].values)

[[{'id': 'qWBaL3',
   'highlight': 'Backed by leading UK VC investors, Fuel Ventures & SFC Capital',
   'created_at': '2023-04-26 09:24:43',
   'updated_at': '2023-05-15 10:45:25',
   'deleted_at': None},
  {'id': 'lOJ8kB',
   'highlight': '472% growth in monthly revenue from May 22 (+£10k) to May 23 (+£61k)',
   'created_at': '2023-05-15 10:45:39',
   'updated_at': '2023-06-08 09:35:45',
   'deleted_at': None},
  {'id': 'bP1B5r',
   'highlight': 'Opened 5 stores across London & Bristol since launch in 2021',
   'created_at': '2023-05-15 10:45:48',
   'updated_at': '2023-05-15 10:45:48',
   'deleted_at': None},
  {'id': 'b3Jnxd',
   'highlight': '£6.5k subscription MRR (launched in April), 1,000+ 5* reviews & 88 NPS',
   'created_at': '2023-05-15 10:45:56',
   'updated_at': '2023-06-05 14:08:13',
   'deleted_at': None}],
 [{'id': 'ZN7yNb',
   'question': 'What is the subscription plan the company offers?',
   'answer': 'This subscription plan allows customers to save money and get perk

In [10]:
categorical = [
    'product',
    "company.company_industry.name",
    'eis',
    'seis',
    'country',
    'currency',
]
final_full[categorical].dropna().head(2)

product             company.company_industry.name  eis seis  \
0  equity_share_price  Apparel & accessories, home and personal  yes   no   
1  equity_share_price                    Food & beverage (FMCG)   no   no   

   country currency  
0      1.0      GBP  
1    211.0      EUR

In [11]:
numeric = [
    'equity',
    'investment.percentage',
    'investment_fee.percentage',
    # 'stats.investors.total',
    'No. of Investors',
    'stats.views.unique_total',
    'stats.followers.total',
    'stats.views.total',
]
final_full[numeric].dropna().head(2)

equity  investment.percentage  investment_fee.percentage No. of Investors  \
0   5.86                  122.0                       2.49              139   
1   5.17                  114.0                       2.49              171   

   stats.views.unique_total  stats.followers.total  stats.views.total  
0                    4791.0                  350.0             8924.0  
1                    5198.0                  332.0             8355.0

In [12]:
core = [
    "id",
    'name',
    'company.name',
    'url',
    'company',
    # 'Date',
    'dates.activated',
    'dates.funded',
    'dates.closed',
    *categorical,
    *money,
    *numeric,
    *mark_up,
    *complex
]

In [13]:
# Show example for exlucded col
for c in [x for x in final_full.columns if x not in core]:
    try:
        print(f"{c:>50}", final_full[c].dropna()[0])
    except:
        pass

                                              Date 2023-12-06 00:00:00
                                            Amount £491,242.90
                                          url_left https://www.crowdcube.eu/investment/cutbox-barbers-30186
                                           src_url https://www.crowdcube.eu/investment/cutbox-barbers-30186
                                        entr_title Louis, Oz
     enable_email_notification_on_pitch_investment True
                                 primary_sector_id 0.0
                                          can_view True
                                            status funded
                                            hidden False
                                        restricted False
                                      pledges_only False
                                            images [{'id': 'qWLAMl', 'type': 'logo', 'status': 'live', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/files/pitch_pics/original/202305/7459

In [14]:
from w3lib.html import remove_tags
import locale
from locale import atof

lut = {40: 'Canada',
       16: 'Austria',
       1: 'United Kingdom',
       69: 'Estonia',
       75: 'France',
       60: 'Denmark',
       23: 'Belgium',
       42: 'Cayman Islands',
       82: 'Germany',
       84: 'Gibraltar',
       129: 'Luxembourg',
       156: 'Netherlands',
       178: 'Portugal',
       166: 'Norway',
       122: 'Latvia',
       231: 'United States of America',
       212: 'Switzerland',
       205: 'Spain',
       198: 'Singapore',
       211: 'Sweden',
       106: 'Ireland'}

clean = final_full.copy()
clean["country"] = clean.country.map(lambda x: lut[int(x)], na_action="ignore")
clean[money] = clean[money].map(lambda x: float(x[0])/100, na_action="ignore")
clean[mark_up] = clean[mark_up].map(remove_tags, na_action="ignore")
locale.setlocale(locale.LC_NUMERIC, 'en_GB')
clean[numeric] = clean[numeric].astype(str).map(atof, na_action="ignore")
dates = ["dates.activated", "dates.funded", "dates.closed"]
clean[dates] = clean[dates].map(pd.to_datetime)
clean[categorical] = clean[categorical].convert_dtypes("categorical")
clean[["eis", "seis"]] = clean[["eis", "seis"]].map(
    lambda x: x if x.__class__ != list else "_".join(x), na_action="ignore")
clean = clean.convert_dtypes()

dict(clean[core].iloc[0])

{'id': 'lKnKBq',
 'name': 'CUTBOX',
 'company.name': 'CUTBOX LIMITED',
 'url': 'https://www.crowdcube.eu/companies/cutbox-barbers/pitches/lKnKBq',
 'company': 'https://www.crowdcube.eu/companies/cutbox-barbers',
 'dates.activated': Timestamp('2023-06-09 13:41:14'),
 'dates.funded': Timestamp('2023-06-12 08:29:49'),
 'dates.closed': Timestamp('2023-07-05 00:15:06'),
 'product': 'equity_share_price',
 'company.company_industry.name': 'Apparel & accessories, home and personal',
 'eis': 'yes',
 'seis': 'no',
 'country': 'United Kingdom',
 'currency': 'GBP',
 'valuation.pre': 7887879,
 'valuation.post': 8287879,
 'investment.current': 491242.9,
 'investment.target': 400000.0,
 'investment.minimum': 33.26,
 'investment.maximum': 400000,
 'investment.multiple': 33.25721,
 'investment_fee.minimum': 2.49,
 'investment_fee.maximum': 250,
 'stats.investments.today': 0.0,
 'stats.investments.yesterday': 0.0,
 'stats.investments.last_7_days': 0.0,
 'stats.investments.daily_average': 8931,
 'stats.i

In [43]:
d = clean[params+money]#.set_index(params,drop=True).convert_dtypes()
d.Date[d.Date.map(lambda x : x.year<=20)].map(lambda x:x.day).value_counts()#.==2023#.map(lambda x:x.date()).map(pd.to_datetime)

NameError: name 'params' is not defined

In [84]:
people.columns.to_list()

['project_id',
 'dates.funded',
 'first_name',
 'id',
 'index',
 'job_title',
 'last_name',
 'linkedin_url',
 'photo_url',
 'role_id']

In [15]:
import numpy as np
from functools import partial
from currency_converter import CurrencyConverter,ECB_URL
c = CurrencyConverter(fallback_on_missing_rate=True,fallback_on_missing_rate_method="linear_interpolation")
def f(x):
    try:
        return c.convert(amount=1,currency=x[0],date=x[1])
    except:
        return pd.NA
    
params = ["currency","dates.funded"]
d = clean[params+money].convert_dtypes().set_index(params)#.dropna()
d[d.add_suffix("_adj_EUR").columns] = d.mul(d.index.map(f,na_action="ignore"),axis=0).map(partial(np.round,decimals=2))
money2 = d.columns
t = clean.drop(columns=money).join(d[sorted(d.columns)].reset_index(drop=True))
a = t["Amount"].str.split("^(€|£)+",regex=True,expand=True).replace("",pd.NA).dropna(how="all",axis=1)
a.loc[:,1] = a.loc[:,1].map({"£":"GBP","€":"EUR"})
locale.setlocale(locale.LC_NUMERIC, 'en_GB')
a.loc[:,2] = a.loc[:,2].map(atof)
b = t[["Date","dates.funded"]].min(axis=1)
f = CurrencyConverter(ECB_URL,fallback_on_missing_rate=True,fallback_on_missing_rate_method="linear_interpolation")
t["Amount_adj_EUR"] = pd.concat((a,b),axis=1).apply(lambda x: f.convert(date=x[0],amount=x[2],currency=x[1]),axis=1).round(2)
first = ["id","name","url","Date",*dates,*sorted(money2)]
t = t[[*first,*sorted(set(t.columns)-set(first))]]
t.drop(columns=complex).to_csv("../data/adjusted/clean_full.csv", encoding="utf8",index=False)
t

id                                     name  \
0     lKnKBq                                   CUTBOX   
1     bJ1kdZ                             Hooked Foods   
2     qaE20q                 Mapal Aeration Solutions   
3     bvLKxl              Move Technologies Group Ltd   
4     q4Mwol              Move Technologies Group Ltd   
...      ...                                      ...   
1591    <NA>     Kammerling's Investment Holdings Ltd   
1592    <NA>                             Kammerling's   
1593    <NA>                   The Rushmore Group Ltd   
1594    <NA>  The Rushmore Group Ltd - Extended offer   
1595    <NA>                   The Rushmore Group Ltd   

                                                    url       Date  \
0     https://www.crowdcube.eu/companies/cutbox-barb... 2023-12-06   
1     https://www.crowdcube.eu/companies/hooked-food... 2023-06-13   
2     https://www.crowdcube.eu/companies/mapal-aerat... 2023-06-13   
3     https://www.crowdcube.eu/companies/move-techno... 2023-09-06   
4     https://www.crowdcube.eu/companies/move-techno... 2023-09-06   
...                                                 ...        ...   
1591  https://www.crowdcube.eu/investment/kamm-sons-... 2012-12-20   
1592  https://www.crowdcube.eu/investment/kamm-sons-... 2011-10-13   
1593  https://www.crowdcube.eu/investment/the-rushmo... 2013-04-15   
1594  https://www.crowdcube.eu/investment/the-rushmo... 2011-12-21   
1595  https://www.crowdcube.eu/investment/the-rushmo... 2011-11-19   

         dates.activated        dates.funded        dates.closed  \
0    2023-06-09 13:41:14 2023-06-12 08:29:49 2023-07-05 00:15:06   
1    2023-06-13 09:16:28 2023-06-13 09:22:30 2023-07-01 00:15:11   
2    2023-05-03 13:48:47 2023-06-13 18:50:45 2023-06-21 00:15:08   
3                    NaT 2023-06-09 08:17:41 2023-06-09 08:17:41   
4                    NaT 2023-06-09 07:48:28 2023-06-09 07:48:28   
...                  ...                 ...                 ...   
1591                 NaT                 NaT                 NaT   
1592                 NaT                 NaT                 NaT   
1593                 NaT                 NaT                 NaT   
1594                 NaT                 NaT                 NaT   
1595                 NaT                 NaT                 NaT   

      investment.current  investment.current_adj_EUR  investment.maximum  ...  \
0               491242.9                   573359.44              400000  ...   
1              638736.61                   638736.61              560000  ...   
2              463814.41                   540261.40              400000  ...   
3                57200.0                    66670.55                 100  ...   
4               932850.0                  1087301.12                 100  ...   
...                  ...                         ...                 ...  ...   
1591                <NA>                         NaN                <NA>  ...   
1592                <NA>                         NaN                <NA>  ...   
1593                <NA>                         NaN                <NA>  ...   
1594                <NA>                         NaN                <NA>  ...   
1595                <NA>                         NaN                <NA>  ...   

                                       the_idea.content  the_idea.id  \
0     From Starbucks for a caffeine fix to Apple for...       bM5nLb   
1     While seafood consumption is growing, marine e...       qaLg5b   
2     Millions of dollars are wasted each year throu...       bJwoJq   
3                                                  <NA>         <NA>   
4                                                  <NA>         <NA>   
...                                                 ...          ...   
1591                                               <NA>         <NA>   
1592                                               <NA>         <NA>   
1593                                          

In [17]:
ab = cc_full[["dates.activated","team_members"]]#.sort_values("team_members")
ab["year"] = ab["dates.activated"].map(lambda x:pd.to_datetime(x)).dt.year
ab["num_members"] = ab["team_members"].map(len,na_action="ignore")
list(ab.sort_values("num_members",ascending=False)[["num_members","year"]].dropna().values)

/var/folders/t0/lg3jmzv573q7n1cv7kt891y40000gn/T/ipykernel_6376/3984790367.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ab["year"] = ab["dates.activated"].map(lambda x:pd.to_datetime(x)).dt.year
/var/folders/t0/lg3jmzv573q7n1cv7kt891y40000gn/T/ipykernel_6376/3984790367.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ab["num_members"] = ab["team_members"].map(len,na_action="ignore")


[array([   9., 2023.]),
 array([   8., 2023.]),
 array([   8., 2023.]),
 array([   8., 2023.]),
 array([   7., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   3., 2023.]),
 array([2.000e+00, 2.023e+03]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2023.]),
 array([   0., 2020.]),
 array([

In [18]:
ab

dates.activated                                       team_members  \
0                    None                                                 []   
1     2023-06-13 09:16:28  [{'id': 'gb3YGl', 'first_name': 'Tom', 'last_n...   
2                    None                                                 []   
3     2023-06-02 15:06:34  [{'id': '4qn7gl', 'first_name': 'Dimeji', 'las...   
4     2023-05-03 13:48:47                                                 []   
...                   ...                                                ...   
1233  2022-03-15 11:13:07                                                 []   
1234  2021-12-07 16:19:49                                                 []   
1235  2018-09-04 14:02:43                                                 []   
1236  2017-03-15 11:28:17                                                 []   
1237  2016-07-17 21:19:31                                                 []   

        year  num_members  
0        NaN            0  
1     2023.0            6  
2        NaN            0  
3     2023.0            2  
4     2023.0            0  
...      ...          ...  
1233  2022.0            0  
1234  2021.0            0  
1235  2018.0            0  
1236  2017.0            0  
1237  2016.0            0  

[1238 rows x 4 columns]

In [19]:
from currency_converter import CurrencyConverter,ECB_URL

conv = CurrencyConverter(ECB_URL,fallback_on_missing_rate=True,fallback_on_missing_rate_method="linear_interpolation")

for c in ["team_members"]:#complex:
    params = ["dates.funded","id"]
    table = clean.loc[:,[c,*params]].explode(column=c).dropna()
    table = table.rename(columns={"id":"project_id"})
    params = ["dates.funded","project_id"]
    #normalized = 
    #if("id" not in normalized.columns):

    table = pd.concat((table[params].reset_index(drop=True),
                       pd.json_normalize(table[c]).convert_dtypes().reset_index(drop=True)),
                       axis=1)
    objects = table.select_dtypes(object).dropna(axis=1,how="all")
    #break
    if not objects.empty:
        print(c)
        for obj in objects.columns:
            table[[obj,"currency"]] = pd.DataFrame(table[obj].fillna("").to_list())
            table[obj] = table[obj].div(100)
            index = ["currency","dates.funded"]
            table = table.dropna(subset=index).set_index(index,drop=True)
            table[f"exchange_rate_{obj}"] = table.index.map(lambda x:conv.convert(amount=1,currency=x[0],date=x[1]),na_action="ignore")
            table[obj + "_adj_EUR"] = table[obj].mul(table[f"exchange_rate_{obj}"],axis=0).round(2)
    table = table.reset_index()
    table = table[["project_id"]+sorted(table.drop(columns="project_id").columns)]
    #table.to_csv(f"../data/adjusted/{c}.csv", encoding="utf8",index=False)
table.dropna()



project_id        dates.funded first_name      id  index         job_title  \
0      lKnKBq 2023-06-12 08:29:49         Oz  EbMN5q      0  Co-Founder & CEO   
1      lKnKBq 2023-06-12 08:29:49      Louis  9Z7yNq      1  Co-Founder & COO   
2      lKnKBq 2023-06-12 08:29:49     James   PbvgGq      2   Head of Finance   
3      lKnKBq 2023-06-12 08:29:49    Dorian   ebw88q      3           Advisor   
4      lKnKBq 2023-06-12 08:29:49    Philip   XlEVaZ      4           Advisor   
..        ...                 ...        ...     ...    ...               ...   
95     bwL9Jq 2023-06-22 12:23:57       Adam  KbVxVl     95   Founder and CEO   
96     bwL9Jq 2023-06-22 12:23:57     Viktor  4qn9Bb     96   Founder and COO   
97     bwL9Jq 2023-06-22 12:23:57     Shahid  elejzZ     97               CTO   
98     bwL9Jq 2023-06-22 12:23:57       Paul  2bdoAZ     98               CFO   
99     bwL9Jq 2023-06-22 12:23:57      James  6qa8mb     99        VP Product   

      last_name                                       linkedin_url  \
0          Oboh  https://www.linkedin.com/in/osajie-oboh-b5291a...   
1   Angel Scott     https://www.linkedin.com/in/louis-angel-scott/   
2       Crowson  https://www.linkedin.com/in/james-crowson-8409...   
3         Waite  https://www.linkedin.com/in/dorian-waite-9207b...   
4          Raub                 https://www.linkedin.com/in/praub/   
..          ...                                                ...   
95        Dodds              https://www.linkedin.com/in/adamdodds   
96      Nebehaj          https://www.linkedin.com/in/viktornebehaj   
97       Naveed           https://www.linkedin.com/in/shahidnaveed   
98     Brooking  https://www.linkedin.com/in/paul-brooking-2a61...   
99         Bell    https://www.linkedin.com/in/james-bell-95754622   

                                            photo_url  role_id  
0   https://files-crowdcube-com.s3.amazonaws.com/f...        1  
1   https://files-crowdcube-com.s3.amazonaws.com/f...        1  
2   https://files-crowdcube-com.s3.amazonaws.com/f...        1  
3   https://files-crowdcube-com.s3.amazonaws.com/f...        2  
4   https://files-crowdcube-com.s3.amazonaws.com/f...        2  
..                                                ...      ...  
95  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
96  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
97  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
98  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
99  https://files-crowdcube-com.s3.amazonaws.com/f...        1  

[99 rows x 10 columns]

In [20]:
complex

['highlights',
 'faqs',
 'team_members',
 'rewards',
 'shares',
 'regulators',
 'remaining_tax_relief_allocation']

<h3>Export files

In [99]:
#clean[core].to_csv("../data/clean_core.csv", encoding="utf8")
#clean[core].to_json("../data/clean_core.json")
#clean[core].to_excel("../data/clean_core.xlsx")

In [100]:
#clean.to_csv("../data/adjusted/clean_full.csv", encoding="utf8",index=False)
#clean.to_json("../data/clean_full.json")
#clean.to_excel("../data/clean_full.xlsx")

In [101]:
#clean.drop(columns=complex).to_csv("../data/adjusted/clean_full.csv", encoding="utf8",index=False)

In [21]:
base = sorted(set(core)-set(["id"]))
rest = sorted(set(clean.columns)-set(["id"]))

clean[["id",*rest]]

id       Amount       Date  No. of Investors    call_to_action  \
0     lKnKBq  £491,242.90 2023-12-06               139                     
1     bJ1kdZ  €638,736.61 2023-06-13               171                     
2     qaE20q  £463,814.41 2023-06-13               427  Get early access   
3     bvLKxl      £57,200 2023-09-06               132  Get early access   
4     q4Mwol     £932,850 2023-09-06              1071  Get early access   
...      ...          ...        ...               ...               ...   
1591    <NA>     £325,000 2012-12-20                65              <NA>   
1592    <NA>     £180,000 2011-10-13                85              <NA>   
1593    <NA>     £500,000 2013-04-15                73              <NA>   
1594    <NA>     £500,000 2011-12-21                69              <NA>   
1595    <NA>   £1,025,000 2011-11-19               142              <NA>   

      can_view                                            company  \
0         True  https://www.crowdcube.eu/companies/cutbox-barbers   
1         True    https://www.crowdcube.eu/companies/hooked-foods   
2         True  https://www.crowdcube.eu/companies/mapal-aerat...   
3         True  https://www.crowdcube.eu/companies/move-techno...   
4         True  https://www.crowdcube.eu/companies/move-techno...   
...        ...                                                ...   
1591      <NA>       https://www.crowdcube.eu/companies/kamm-sons   
1592      <NA>       https://www.crowdcube.eu/companies/kamm-sons   
1593      <NA>  https://www.crowdcube.eu/companies/the-rushmor...   
1594      <NA>  https://www.crowdcube.eu/companies/the-rushmor...   
1595      <NA>  https://www.crowdcube.eu/companies/the-rushmor...   

      company.company_industry  company.company_industry.id  \
0                         <NA>                            2   
1                         <NA>                           12   
2                         <NA>                            8   
3                         <NA>                         <NA>   
4                         <NA>                         <NA>   
...                        ...                          ...   
1591                      <NA>                         <NA>   
1592                      <NA>                         <NA>   
1593                      <NA>                         <NA>   
1594                      <NA>                         <NA>   
1595                      <NA>                         <NA>   

                 company.company_industry.name  ... the_people  \
0     Apparel & accessories, home and personal  ...       <NA>   
1                       Food & beverage (FMCG)  ...       <NA>   
2                        Energy and renewables  ...       <NA>   
3                                         <NA>  ...       <NA>   
4                                         <NA>  ...       <NA>   
...                                        ...  ...        ...   
1591                                      <NA>  ...       <NA>   
1592                                      <NA>  ...       <NA>   
1593                                      <NA>  ...       <NA>   
1594                                      <NA>  ...       <NA>   
1595                                      <NA>  ...       <NA>   

                                     the_people.content the_people.id  \
0                                                  <NA>          <NA>   
1                                                  <NA>          <NA>   
2     Zeev Fisher, CEO and co-founder: Many years of...        bLkMRZ   
3                                                  <NA>          <NA>   
4                                                  <NA>          <NA>   
...                                                 ...           ...   
1591                                               <NA>          <NA>   
1592                                               <NA>          <NA>   
1593                                               <NA>      

In [104]:
cc_reg = pd.DataFrame()
og = t.drop(columns=complex)
dict(og.dtypes)

{'id': string[python],
 'name': string[python],
 'url': string[python],
 'Date': dtype('<M8[ns]'),
 'dates.activated': dtype('<M8[ns]'),
 'dates.funded': dtype('<M8[ns]'),
 'dates.closed': dtype('<M8[ns]'),
 'investment.current': Float64Dtype(),
 'investment.current_adj_EUR': dtype('float64'),
 'investment.maximum': Int64Dtype(),
 'investment.maximum_adj_EUR': dtype('float64'),
 'investment.minimum': Float64Dtype(),
 'investment.minimum_adj_EUR': dtype('float64'),
 'investment.multiple': Float64Dtype(),
 'investment.multiple_adj_EUR': dtype('float64'),
 'investment.target': Float64Dtype(),
 'investment.target_adj_EUR': dtype('float64'),
 'investment_fee.maximum': Int64Dtype(),
 'investment_fee.maximum_adj_EUR': dtype('float64'),
 'investment_fee.minimum': Float64Dtype(),
 'investment_fee.minimum_adj_EUR': dtype('float64'),
 'stats.investments.daily_average': Int64Dtype(),
 'stats.investments.daily_average_adj_EUR': dtype('float64'),
 'stats.investments.largest': Float64Dtype(),
 'stats

In [13]:
import pandas as pd
people = pd.read_csv("../data/adjusted/team_members.csv")
people
#cc_full.owner

project_id         dates.funded first_name      id  index  \
0      lKnKBq  2023-06-12 08:29:49         Oz  EbMN5q      0   
1      lKnKBq  2023-06-12 08:29:49      Louis  9Z7yNq      1   
2      lKnKBq  2023-06-12 08:29:49     James   PbvgGq      2   
3      lKnKBq  2023-06-12 08:29:49    Dorian   ebw88q      3   
4      lKnKBq  2023-06-12 08:29:49    Philip   XlEVaZ      4   
..        ...                  ...        ...     ...    ...   
95     bwL9Jq  2023-06-22 12:23:57       Adam  KbVxVl     95   
96     bwL9Jq  2023-06-22 12:23:57     Viktor  4qn9Bb     96   
97     bwL9Jq  2023-06-22 12:23:57     Shahid  elejzZ     97   
98     bwL9Jq  2023-06-22 12:23:57       Paul  2bdoAZ     98   
99     bwL9Jq  2023-06-22 12:23:57      James  6qa8mb     99   

           job_title    last_name  \
0   Co-Founder & CEO         Oboh   
1   Co-Founder & COO  Angel Scott   
2    Head of Finance      Crowson   
3            Advisor        Waite   
4            Advisor         Raub   
..               ...          ...   
95   Founder and CEO        Dodds   
96   Founder and COO      Nebehaj   
97               CTO       Naveed   
98               CFO     Brooking   
99        VP Product         Bell   

                                         linkedin_url  \
0   https://www.linkedin.com/in/osajie-oboh-b5291a...   
1      https://www.linkedin.com/in/louis-angel-scott/   
2   https://www.linkedin.com/in/james-crowson-8409...   
3   https://www.linkedin.com/in/dorian-waite-9207b...   
4                  https://www.linkedin.com/in/praub/   
..                                                ...   
95              https://www.linkedin.com/in/adamdodds   
96          https://www.linkedin.com/in/viktornebehaj   
97           https://www.linkedin.com/in/shahidnaveed   
98  https://www.linkedin.com/in/paul-brooking-2a61...   
99    https://www.linkedin.com/in/james-bell-95754622   

                                            photo_url  role_id  
0   https://files-crowdcube-com.s3.amazonaws.com/f...        1  
1   https://files-crowdcube-com.s3.amazonaws.com/f...        1  
2   https://files-crowdcube-com.s3.amazonaws.com/f...        1  
3   https://files-crowdcube-com.s3.amazonaws.com/f...        2  
4   https://files-crowdcube-com.s3.amazonaws.com/f...        2  
..                                                ...      ...  
95  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
96  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
97  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
98  https://files-crowdcube-com.s3.amazonaws.com/f...        1  
99  https://files-crowdcube-com.s3.amazonaws.com/f...        1  

[100 rows x 10 columns]

In [ ]:
#sustainabillity

In [122]:
#success
cc_reg["success_target"] = og["investment.percentage"] >= 100
cc_reg["success_percentage_raised"]  = og["investment.percentage"]
cc_reg["funding_amount"]  = og["investment.current_adj_EUR"]
cc_reg["no_investors"]  = og['No. of Investors']
cc_reg["average_pledge"]  = cc_reg.funding_amount / cc_reg.no_investors
cc_reg["speed_of_investment"]  = og["dates.funded"]-og["dates.activated"]

In [129]:
#social capital
#cc_reg["social_capital_linkedin"]
#cc_reg["gender"]
#cc_reg["education"]
#cc_reg["social_media"]


In [123]:
#legitimacy

#cc_reg["Grant"]
#cc_reg["Award"]
#cc_reg["Award"]

In [113]:
#industry


Index(['id', 'name', 'url', 'Date', 'dates.activated', 'dates.funded',
       'dates.closed', 'investment.current', 'investment.current_adj_EUR',
       'investment.maximum',
       ...
       'the_idea.content', 'the_idea.id', 'the_idea.media', 'the_people',
       'the_people.content', 'the_people.id', 'the_people.media',
       'translations_available', 'updated_at', 'url_left'],
      dtype='object', length=165)

In [124]:
#human capital


In [125]:
# financial considerations


In [126]:
#control variable

In [127]:
#communication

In [128]:
#campaign